class ExecutionStore:
    def __init__(self):
        self.training_time_without_weights = []
        self.training_time_with_fsl = []
        self.training_time_with_fsl_posthoc = []
        self.silhouette_without_weights = []
        self.silhouette_with_fsl = []
        self.silhouette_with_fsl_posthoc = []
        self.f1_scores_without_weights = []
        self.f1_scores_with_fsl = []
        self.f1_scores_with_fsl_posthoc = []
        self.accuracy_without_weights = []
        self.accuracy_with_fsl = []
        self.accuracy_with_fsl_posthoc = []
        self.precision_without_weights = []
        self.precision_with_fsl = []
        self.precision_with_fsl_posthoc = []
        self.recall_without_weights = []
        self.recall_with_fsl = []
        self.recall_with_fsl_posthoc = []
        self.pifs_with_fsl = []
        self.pifs_with_fsl_posthoc = []
        self.psfi_with_fsl = []
        self.psfi_with_fsl_posthoc = []
        self.feature_weights_results_with_fsl = []
        self.feature_weights_results_with_fsl_posthoc = []