class ExecutionStore:
    def __init__(self):
        self.training_time_without_weights = []
        self.training_time_with_fsl = []
        self.training_time_with_fsl_posthoc = []
        self.training_time_integrated_gradients = []
        self.training_time_noise_tunnel = []
        self.training_time_deep_lift = []
        self.training_time_gradient_shap = []
        self.training_time_feature_ablation = []
        self.silhouette_without_weights = []
        self.silhouette_with_integrated_gradients = []
        self.silhouette_with_noise_tunnel = []
        self.silhouette_with_deep_lift = []
        self.silhouette_with_gradient_shap = []
        self.silhouette_with_feature_ablation = []
        self.silhouette_with_fsl = []
        self.silhouette_with_fsl_posthoc = []
        self.f1_scores_without_weights = []
        self.f1_scores_with_fsl = []
        self.f1_scores_with_fsl_posthoc = []
        self.accuracy_without_weights = []
        self.accuracy_with_fsl = []
        self.accuracy_with_fsl_posthoc = []
        self.precision_without_weights = []
        self.precision_with_fsl = []
        self.precision_with_fsl_posthoc = []
        self.recall_without_weights = []
        self.recall_with_fsl = []
        self.recall_with_fsl_posthoc = []
        self.pifs_with_integrated_gradients = []
        self.pifs_with_noise_tunnel = []
        self.pifs_with_deep_lift = []
        self.pifs_with_gradient_shap = []
        self.pifs_with_feature_ablation = []
        self.pifs_with_fsl = []
        self.pifs_with_fsl_posthoc = []
        self.psfi_with_integrated_gradients = []
        self.psfi_with_noise_tunnel = []
        self.psfi_with_deep_lift = []
        self.psfi_with_gradient_shap = []
        self.psfi_with_feature_ablation = []
        self.psfi_with_fsl = []
        self.psfi_with_fsl_posthoc = []
        self.feature_weights_fsl = []
        self.feature_weights_fsl_posthoc = []
        self.feature_weights_integrated_gradients = []
        self.feature_weights_noise_tunnel = []
        self.feature_weights_deep_lift = []
        self.feature_weights_gradient_shap = []
        self.feature_weights_feature_ablation = []
        self.erasure_results = {
            "Integrated Gradients": {"f1": [], "acc": [], "prec": [], "rec": []},
            "Noise Tunnel": {"f1": [], "acc": [], "prec": [], "rec": []},
            "Deep Lift": {"f1": [], "acc": [], "prec": [], "rec": []},
            "Gradient SHAP": {"f1": [], "acc": [], "prec": [], "rec": []},
            "Feature Ablation": {"f1": [], "acc": [], "prec": [], "rec": []},
            "Post-hoc FSL": {"f1": [], "acc": [], "prec": [], "rec": []}
        }

class PretrainedExecutionStore:
    def __init__(self):
        self.training_time_without_weights = []
        self.training_time_with_fsl_posthoc = []
        self.silhouette_without_weights = []
        self.silhouette_with_integrated_gradients = []
        self.silhouette_with_noise_tunnel = []
        self.silhouette_with_deep_lift = []
        self.silhouette_with_gradient_shap = []
        self.silhouette_with_feature_ablation = []
        self.silhouette_with_fsl_posthoc = []
        self.f1_scores_without_weights = []
        self.f1_scores_with_fsl_posthoc = []
        self.accuracy_without_weights = []
        self.accuracy_with_fsl_posthoc = []
        self.precision_without_weights = []
        self.precision_with_fsl_posthoc = []
        self.recall_without_weights = []
        self.recall_with_fsl_posthoc = []
        self.feature_weights_fsl_posthoc = []
        self.feature_weights_integrated_gradients = []
        self.feature_weights_noise_tunnel = []
        self.feature_weights_deep_lift = []
        self.feature_weights_gradient_shap = []
        self.feature_weights_feature_ablation = []